### PR TITLE
fix: check that idp is like iss for allowed users

### PR DESCRIPTION
**Pull request by loekensgard**

### CODE REVIEW

**Review by h3rmanj — CHANGES_REQUESTED** [review]
Rename to `DenyGuestsRequirement`.

For our case, I think we could use the pattern of the requirement class implementing both requirement and handler, skipping the need to register the handler in dependency injection.

**Comment by JonasKs** [comment]
Did you opt for not implementing tests in the template? 😊

my tests: https://github.com/Intility/fastapi-azure-auth/blob/disallow_guest_users/tests/test_guest_user.py

**Comment by h3rmanj** [comment]
Adding a test project to the template is a separate issue and should probably be done in another pr

**Comment by loekensgard** [comment]
> Did you opt for not implementing tests in the template? 😊
> 
> my tests: https://github.com/Intility/fastapi-azure-auth/blob/disallow_guest_users/tests/test_guest_user.py

@h3rmanj I was wondering whether we should incorporate tests into the template. If the answer is yes, do you suggest creating a new project or simply a folder labeled 'tests'?

**Comment by h3rmanj** [comment]
When we add it the structure should be something like;

```
src/[path/to/project]
tests/[path/to/project].Tests.[Integration|Unit]
```

**Pull request merged**
